title: Miguel Angel Henao Perez # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software engineer working as a fullstack developer with experience in <b>.Net, .Net Core and Angular</b> frameworks
  <br><br>
  I've been working with web applications since 2017 and I wanted to have a small portfolio with personal projects.
  These are not complex applications, just some random ideas that I develop when I have some free time. :) 
  <br>
  <a href="https://www.linkedin.com/in/miguel-%C3%A1ngel-henao-p%C3%A9rez-715601165/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
